-- ============================================================================
-- Prism install script — POSTGRESQL
--
-- Everything Prism requires inside your Postgres database: two new schemas
-- (prism_internal, prism_exports) holding Prism's internal tables and roles.
-- It touches none of your own schemas or data.
--
-- ⚠️ SCOPE: Postgres cannot query across databases, so this script creates
-- its schemas inside the ONE database that holds the source tables you want
-- standardized. One Prism installation covers one database.
--
-- Run as a superuser / owner-capable role, CONNECTED TO THAT DATABASE:
--   psql -h <host> -U postgres -d <database> -f 01_internal_tables.postgres.sql
--
-- ⚠️ Re-running this script RESETS Prism's internal tables (confirmed
-- mappings, queued values). Run it once at install time; re-run only if you
-- intend to start Prism over from scratch.
--
-- Two choices you may notice in the definitions:
--   * Identifiers are lowercase snake_case (Postgres folds unquoted
--     identifiers to lowercase), and the schemas are prefixed prism_ so they
--     cannot collide with your own schemas.
--   * Columns that participate in matching use COLLATE "C" (byte-wise
--     comparison), so a database created with a nondeterministic ICU
--     collation cannot silently merge values Prism must keep distinct.
-- ============================================================================

-- ── Schemas ─────────────────────────────────────────────────────────────────
-- prism_internal: Prism's data plane (lookup tables, queue, run state).
-- prism_exports:  default destination for lookup-table exports.
CREATE SCHEMA IF NOT EXISTS prism_internal;
CREATE SCHEMA IF NOT EXISTS prism_exports;

-- ============================================================================
-- DATA-PLANE TABLES (dropped and recreated — this is what makes a re-run a
-- full reset of Prism's internal data)
-- ============================================================================

DROP TABLE IF EXISTS prism_internal.literal_alias_matches;
DROP TABLE IF EXISTS prism_internal.approved_alias_names;
DROP TABLE IF EXISTS prism_internal.pipeline_queue;
DROP TABLE IF EXISTS prism_internal.one_time_file_rows;
DROP TABLE IF EXISTS prism_internal.one_time_file_blobs;
DROP TABLE IF EXISTS prism_internal.run_state;
DROP TABLE IF EXISTS prism_internal.validation_log;

-- ----------------------------------------------------------------------------
-- pipeline_queue — values detected by polling, waiting for the next
-- standardization tick. pipeline_id references Prism's app-side pipeline
-- record.
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.pipeline_queue (
    queue_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id      INT           NOT NULL,
    literal_value    VARCHAR(800) COLLATE "C" NOT NULL,
    source_frequency INT           NOT NULL DEFAULT 1,
    detected_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_pipeline_queue UNIQUE (pipeline_id, literal_value)
);

-- ----------------------------------------------------------------------------
-- approved_alias_names — catalog of confirmed canonical names.
-- domain_id is a historical column name: it holds the per-column spec id
-- that scopes each column's lookup.
--
-- Uniqueness: Postgres treats NULLs as DISTINCT in unique
-- constraints, which would allow unlimited scopeless (NULL domain_id)
-- duplicates of one name. The partial index below restores the "at most ONE
-- scopeless row per name" guarantee the app relies on. (Postgres 15 has
-- NULLS NOT DISTINCT; the partial index works on the 13+ floor.)
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.approved_alias_names (
    alias_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_name   VARCHAR(450) COLLATE "C" NOT NULL,
    domain_id    INT           NULL,      -- Prism's per-column spec id (lookup scope; historical name)
    usage_count  INT           NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ   NULL,
    CONSTRAINT uq_approved_alias_names UNIQUE (alias_name, domain_id)
);
CREATE UNIQUE INDEX uq_aan_scopeless
  ON prism_internal.approved_alias_names (alias_name) WHERE domain_id IS NULL;

-- ----------------------------------------------------------------------------
-- literal_alias_matches — confirmed literal → alias mappings.
-- normalized_value = normalizeLiteral(literal_value), computed in the APP at
-- write time (there is no SQL-side normalize function on this warehouse).
-- Every INSERT/upsert must set it. Indexed for the staging-table joins.
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.literal_alias_matches (
    match_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    literal_value    VARCHAR(800) COLLATE "C" NOT NULL,
    normalized_value VARCHAR(800) COLLATE "C" NULL,
    alias_id         INT           NOT NULL
                     REFERENCES prism_internal.approved_alias_names(alias_id),
    domain_id        INT           NULL,  -- Prism's per-column spec id (denormalized from alias)
    run_id           INT           NOT NULL,  -- Prism's app-side run id (0 = seed sentinel)
    confirmed_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);
-- UNIQUE rather than plain indexes, and this is load-bearing twice over:
-- (1) they are the ON CONFLICT targets for the bulk upsert path (Postgres has
-- no MERGE on the 13+ floor); (2) they mechanically ENFORCE the documented
-- invariant "at most one row per (normalized_value, spec)". The partial index covers the
-- scopeless (NULL domain_id) case — Postgres unique treats NULLs as distinct.
CREATE UNIQUE INDEX uq_lam_norm_scoped
  ON prism_internal.literal_alias_matches (normalized_value, domain_id);
CREATE UNIQUE INDEX uq_lam_norm_scopeless
  ON prism_internal.literal_alias_matches (normalized_value) WHERE domain_id IS NULL;

-- ----------------------------------------------------------------------------
-- one_time_file_rows — row snapshot for a ONE-TIME standardization sourced
-- from an uploaded file or a Google Sheet. Keyed by the session nonce
-- (one-time sessions have no pipeline_id). Held here, in your database,
-- because the rows contain your data values (data residency).
-- column_data is JSONB — inherently valid JSON, no CHECK needed.
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.one_time_file_rows (
    row_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_nonce VARCHAR(100)  NOT NULL,
    row_num       INT           NOT NULL,
    column_data   JSONB         NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_otfr_session
  ON prism_internal.one_time_file_rows (session_nonce, row_num);

-- ----------------------------------------------------------------------------
-- one_time_file_blobs — original uploaded file bytes (base64, chunked), so a
-- one-time standardization can hand back your own file with only the
-- standardized cells changed. Stored here, in your database, for the same
-- data-residency reason as run_state.
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.one_time_file_blobs (
    session_nonce VARCHAR(100)  NOT NULL,
    chunk_num     INT           NOT NULL,
    file_name     VARCHAR(400)  NOT NULL,
    file_kind     VARCHAR(10)   NOT NULL,
    sheet_name    VARCHAR(400)  NULL,
    header_row    INT           NOT NULL,
    data          TEXT          NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (session_nonce, chunk_num)
);

-- ----------------------------------------------------------------------------
-- run_state — the run review state blob (data residency).
-- One JSONB blob per run holding the full grouping/review state, which
-- contains your distinct column values. It lives here, in YOUR database, so
-- no data values ever rest in the Prism application's own storage (which
-- keeps only run metadata). The optimistic-concurrency revision lives INSIDE
-- the blob (rev key; missing = 0). run_id references Prism's app-side run
-- record.
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.run_state (
    run_id      INT           NOT NULL PRIMARY KEY,
    state       JSONB         NULL,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- validation_log — append-only audit trail of export-referee decisions.
-- Contains literal source values, so it lives warehouse-side (data residency).
-- ----------------------------------------------------------------------------
CREATE TABLE prism_internal.validation_log (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    literal_value       VARCHAR(800)  NOT NULL,
    run_id              INT           NULL,
    original_alias_name VARCHAR(450)  NULL,
    user_changed_to     VARCHAR(450)  NULL,
    llm_decision        VARCHAR(20)   NULL,  -- 'user' | 'original'
    decided_at          TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ============================================================================
-- ROLES AND GRANTS
-- Prism's least-privilege access model, as cluster-wide NOLOGIN roles
-- (CREATE ROLE is cluster-scoped in Postgres, hence the IF-NOT-EXISTS
-- guards via DO blocks).
-- ============================================================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prism_service') THEN
    CREATE ROLE prism_service NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prism_data_admin') THEN
    CREATE ROLE prism_data_admin NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prism_readonly') THEN
    CREATE ROLE prism_readonly NOLOGIN;
  END IF;
END $$;

-- Service role: full data access on prism_internal, create/replace export
-- tables and views in prism_exports, staging tables in prism_internal.
GRANT USAGE, CREATE ON SCHEMA prism_internal TO prism_service;
GRANT USAGE, CREATE ON SCHEMA prism_exports  TO prism_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA prism_internal TO prism_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA prism_exports  TO prism_service;
-- Identity columns are backed by sequences — inserts need sequence USAGE.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA prism_internal TO prism_service;

-- Human maintenance role: direct data access on prism_internal only
-- (break-glass; grant to a person when a concrete need appears, revoke after).
GRANT USAGE ON SCHEMA prism_internal TO prism_data_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA prism_internal TO prism_data_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA prism_internal TO prism_data_admin;

-- Read-only tier (reserved).
GRANT USAGE ON SCHEMA prism_internal TO prism_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA prism_internal TO prism_readonly;

-- ── Service login (template — run with real values; never commit a password) ─
-- The Prism backend connects as a machine identity, never a person:
--
--   CREATE ROLE prism_svc LOGIN PASSWORD '<strong generated password>';
--   GRANT prism_service TO prism_svc;
--   ALTER ROLE prism_svc SET statement_timeout = '600s';
--
-- Kill switch (instant, customer-controlled):  ALTER ROLE prism_svc NOLOGIN;
--
-- For each SOURCE schema Prism should read (one block per schema, run in this
-- same database):
--   GRANT USAGE ON SCHEMA <schema> TO prism_service;
--   GRANT SELECT ON ALL TABLES IN SCHEMA <schema> TO prism_service;
--   -- Future tables (the FUTURE TABLES analog). ⚠️ FOOTGUN: default
--   -- privileges only apply to tables created by the role that runs this
--   -- statement — run it AS (or FOR) every role that creates tables in the
--   -- schema, e.g. FOR ROLE app_owner:
--   ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT SELECT ON TABLES TO prism_service;
--
-- ── Verification ─────────────────────────────────────────────────────────────
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'prism_internal';  -- 7 tables
-- SELECT rolname FROM pg_roles WHERE rolname LIKE 'prism%';
