-- ============================================================================
-- Prism DEMO / DEV DATA — POSTGRESQL
--
-- DEV AND DEMO SERVERS ONLY — never run on a customer database. Customers run
-- only 01_internal_tables.postgres.sql (served by the setup wizard); this file
-- carries the fake source data:
--   * test_sources.raw_mobile_carriers_short — the two-column demo source
--     table with sample carrier/company values
--
-- Postgres cannot query across databases, so — unlike the Snowflake/mssql
-- demos, which use a separate TEST_DB — the demo source lives in a
-- test_sources SCHEMA inside the same database as the Prism install.
--
-- Run AFTER 01_internal_tables.postgres.sql (same database):
--   psql -h <host> -U postgres -d <database> -f 02_demo_data.postgres.sql
-- or via the dev runner (runs both files):  cd stand-ui && npm run pg:install
-- Re-running resets the demo source table (DROP + CREATE).
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS test_sources;

DROP TABLE IF EXISTS test_sources.raw_mobile_carriers_short;

-- row_id identity PK: gives the table a primary key so the PK ordering tier
-- of export builds can be exercised in dev. Keyless behavior is tested by
-- simply not creating one on a copy.
CREATE TABLE test_sources.raw_mobile_carriers_short (
    row_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_carrier_value VARCHAR(200) COLLATE "C" NULL,
    raw_company_value VARCHAR(200) COLLATE "C" NULL
);

INSERT INTO test_sources.raw_mobile_carriers_short (raw_carrier_value, raw_company_value) VALUES
('AT&T', 'Goldman Sachs'),
('ATT', 'Goldman Sachs & Co'),
('A T & T', 'Goldman Sachs Group'),
('American Telephone and Telegraph', 'JPMorgan'),
('American Telephone & Telegraph Company', 'JP Morgan Chase'),
('AT and T', 'JPMorgan Chase & Co.'),
('Verizon', 'McKinsey'),
('Verizon Wireless', 'McKinsey & Company'),
('Verizon Wirless', 'McKinsey and Company Inc'),
('VZW', 'Deloitte'),
('Verizon Communications', 'Deloitte LLP'),
('T-Mobile', 'Deloitte Touche Tohmatsu'),
('T Mobile', 'PricewaterhouseCoopers'),
('TMobile', 'PwC'),
('T-Mobile USA', 'Pricewaterhouse Coopers LLP'),
('Sprint', 'Ernst & Young'),
('Sprint PCS', 'EY'),
('Boost Mobile', 'Ernst and Young LLP'),
('Boost', 'KPMG'),
('Cricket', 'KPMG International'),
('Cricket Wireless', 'Bain & Company'),
('MetroPCS', 'Bain and Co'),
('Metro PCS', 'Bain'),
('Metro by T-Mobile', 'Boston Consulting Group'),
('US Cellular', 'BCG'),
('USCellular', 'The Boston Consulting Group'),
('Capital One', 'Accenture'),
('C1', 'Accenture PLC');

-- Dev grants: let the service role read the demo source (mirrors the source
-- schema grants a customer's admin runs — see the template in
-- 01_internal_tables.postgres.sql).
GRANT USAGE ON SCHEMA test_sources TO prism_service;
GRANT SELECT ON ALL TABLES IN SCHEMA test_sources TO prism_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA test_sources GRANT SELECT ON TABLES TO prism_service;

-- ── Verification ─────────────────────────────────────────────────────────────
-- SELECT COUNT(*) FROM test_sources.raw_mobile_carriers_short;  -- 28
