USE DATABASE STAND_DB;

-- ============================================================================
-- ROLE DEFINITIONS
-- Three-tier role structure for data standardization system
-- ============================================================================

-- STAND_ADMIN: Full administrative access to internal tables and system management
CREATE ROLE IF NOT EXISTS STAND_ADMIN;

-- STAND_USER: Standard users who can execute standardization procedures
CREATE ROLE IF NOT EXISTS STAND_USER;

-- STAND_VIEWER: Read-only access to public views (future)
CREATE ROLE IF NOT EXISTS STAND_VIEWER;

-- ============================================================================
-- DATABASE AND SCHEMA GRANTS
-- ============================================================================

-- All roles get USAGE on the database
GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_ADMIN;
GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_USER;
GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_VIEWER;

-- All roles get USAGE on the public API schema
GRANT USAGE ON SCHEMA STAND_DB.STAND TO ROLE STAND_ADMIN;
GRANT USAGE ON SCHEMA STAND_DB.STAND TO ROLE STAND_USER;
GRANT USAGE ON SCHEMA STAND_DB.STAND TO ROLE STAND_VIEWER;

-- Only STAND_ADMIN gets access to internal schema
GRANT USAGE ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN;

-- ============================================================================
-- PROCEDURE GRANTS (Public API in STAND schema)
-- ============================================================================

-- STAND_USER and STAND_ADMIN can execute procedures
GRANT USAGE ON PROCEDURE STAND_DB.STAND.CREATE_RUN(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE STAND_USER;
GRANT USAGE ON PROCEDURE STAND_DB.STAND.CREATE_RUN(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE STAND_ADMIN;
GRANT USAGE ON PROCEDURE STAND_DB.STAND.REFRESH_ALIAS_SUMMARY(INTEGER) TO ROLE STAND_USER;
GRANT USAGE ON PROCEDURE STAND_DB.STAND.REFRESH_ALIAS_SUMMARY(INTEGER) TO ROLE STAND_ADMIN;
GRANT USAGE ON PROCEDURE STAND_DB.STAND.REFRESH_TOKENS_SUMMARY(INTEGER) TO ROLE STAND_USER;
GRANT USAGE ON PROCEDURE STAND_DB.STAND.REFRESH_TOKENS_SUMMARY(INTEGER) TO ROLE STAND_ADMIN;

-- Grant on future procedures in STAND schema
GRANT USAGE ON ALL PROCEDURES IN SCHEMA STAND_DB.STAND TO ROLE STAND_USER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA STAND_DB.STAND TO ROLE STAND_ADMIN;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STAND_DB.STAND TO ROLE STAND_USER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA STAND_DB.STAND TO ROLE STAND_ADMIN;

-- ============================================================================
-- INTERNAL TABLE GRANTS (STAND_INTERNAL schema)
-- Only STAND_ADMIN has access - these are not part of the customer contract
-- ============================================================================

-- Admin gets full access to all internal tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN;

-- Specific table grants for STAND_ADMIN
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_DATA_TYPE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_ALIAS_STATUS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_ALIAS_VALUE_SOURCE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_ALIAS_SUMMARY_KEY_TYPE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.USER_TYPE_OPTIONS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_RUN_MODE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_RUN_STATUS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_DECISION_STATUS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_APPLY_MODE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_APPLY_STATUS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.LKP_ENTITY_TYPE TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.CLASSIFICATION_METADATA_PROFILES TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.CONCEPTS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.ALIASES TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.ALIAS_SUMMARY TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.TOKENS_SUMMARY TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.ALIAS_ITEMS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.USERS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.RUNS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.RUN_ITEMS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.RUN_APPLIED_TARGETS TO ROLE STAND_ADMIN;
GRANT ALL PRIVILEGES ON TABLE STAND_DB.STAND_INTERNAL.AUDIT_LOG TO ROLE STAND_ADMIN;

-- ============================================================================
-- PUBLIC VIEWS (STAND schema)
-- When public views are created, STAND_VIEWER will get SELECT access
-- ============================================================================

-- Future: Grant SELECT on public views to STAND_VIEWER
-- Example (uncomment when views are created):
-- GRANT SELECT ON ALL VIEWS IN SCHEMA STAND_DB.STAND TO ROLE STAND_VIEWER;
-- GRANT SELECT ON FUTURE VIEWS IN SCHEMA STAND_DB.STAND TO ROLE STAND_VIEWER;

-- ============================================================================
-- ROLE HIERARCHY (Optional)
-- Allows STAND_ADMIN to inherit permissions from lower roles
-- ============================================================================

GRANT ROLE STAND_USER TO ROLE STAND_ADMIN;
GRANT ROLE STAND_VIEWER TO ROLE STAND_USER;

-- ============================================================================
-- USAGE NOTES
-- ============================================================================

-- To assign roles to users:
--   GRANT ROLE STAND_USER TO USER <username>;
--   GRANT ROLE STAND_ADMIN TO USER <username>;
--   GRANT ROLE STAND_VIEWER TO USER <username>;

-- To use a role:
--   USE ROLE STAND_USER;

-- To set a default role for a user:
--   ALTER USER <username> SET DEFAULT_ROLE = STAND_USER;


