import 'server-only';

/**
 * Generates the ordered list of SQL grant statements that must be applied to a
 * Snowflake account for Prism to function. These mirror the ROLES AND GRANTS
 * block at the bottom of 01_internal_tables.sql — keep the two in sync.
 *
 * @param serviceUser  The Snowflake username the app service role is granted to.
 *                     Omit to skip the GRANT ROLE … TO USER statement.
 */
export function buildGrantStatements(serviceUser?: string): string[] {
  const stmts: string[] = [
    // Roles
    `CREATE ROLE IF NOT EXISTS STAND_ADMIN`,
    `CREATE ROLE IF NOT EXISTS STAND_DATA_ADMIN`,
    `CREATE ROLE IF NOT EXISTS STAND_USER`,
    `CREATE ROLE IF NOT EXISTS STAND_VIEWER`,
    // Role hierarchy
    `GRANT ROLE STAND_USER TO ROLE STAND_ADMIN`,
    `GRANT ROLE STAND_VIEWER TO ROLE STAND_USER`,
    // DB visibility for STAND_USER / STAND_VIEWER (STAND_INTERNAL stays private)
    `GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_USER`,
    `GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_VIEWER`,
    // STAND_DB / STAND_INTERNAL — service role
    `GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_ADMIN`,
    `GRANT USAGE ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    `GRANT ALL PRIVILEGES ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    // Current tables
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.DOMAINS TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.PIPELINES TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.PIPELINE_QUEUE TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.PIPELINE_FILE_ROWS TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.RUNS TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.APPROVED_ALIAS_NAMES TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.LITERAL_ALIAS_MATCHES TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.ACCOUNTS TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.INVITATIONS TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.VALIDATION_LOG TO ROLE STAND_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.ONE_TIME_STANDARDIZATIONS TO ROLE STAND_ADMIN`,
    // Future tables / UDFs
    `GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    `GRANT CREATE FUNCTION ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    `GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    `GRANT USAGE ON ALL FUNCTIONS IN SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_ADMIN`,
    `GRANT USAGE ON FUNCTION STAND_DB.STAND_INTERNAL.PRISM_NORMALIZE(VARCHAR) TO ROLE STAND_ADMIN`,
    // STAND_DATA_ADMIN
    `GRANT USAGE ON DATABASE STAND_DB TO ROLE STAND_DATA_ADMIN`,
    `GRANT USAGE ON SCHEMA STAND_DB.STAND_INTERNAL TO ROLE STAND_DATA_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.LITERAL_ALIAS_MATCHES TO ROLE STAND_DATA_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.APPROVED_ALIAS_NAMES TO ROLE STAND_DATA_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.PIPELINES TO ROLE STAND_DATA_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.ONE_TIME_STANDARDIZATIONS TO ROLE STAND_DATA_ADMIN`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE STAND_DB.STAND_INTERNAL.PIPELINE_FILE_ROWS TO ROLE STAND_DATA_ADMIN`,
    `GRANT USAGE ON FUNCTION STAND_DB.STAND_INTERNAL.PRISM_NORMALIZE(VARCHAR) TO ROLE STAND_DATA_ADMIN`,
  ];

  if (serviceUser) {
    const u = serviceUser.replace(/"/g, '""');
    stmts.push(`GRANT ROLE STAND_ADMIN TO USER "${u}"`);
    stmts.push(`GRANT ROLE STAND_DATA_ADMIN TO USER "${u}"`);
  }

  return stmts;
}

export interface GrantResult {
  sql:   string;
  ok:    boolean;
  error: string | null;
}

/** Run all grant statements on an open Snowflake connection. */
export async function applyGrants(
  conn: any,
  serviceUser?: string,
): Promise<GrantResult[]> {
  const statements = buildGrantStatements(serviceUser);
  const results: GrantResult[] = [];

  for (const sql of statements) {
    try {
      await new Promise<void>((resolve, reject) => {
        conn.execute({
          sqlText: sql,
          complete: (err: any) => (err ? reject(err) : resolve()),
        });
      });
      results.push({ sql, ok: true, error: null });
    } catch (err: any) {
      results.push({ sql, ok: false, error: String(err?.message ?? err) });
    }
  }

  return results;
}
