/**
 * Phase P2 exit-criteria test: the Postgres detection engine, LIVE against the
 * docs/DEV_POSTGRES.md container (docs/POSTGRES_PORT_PLAN.md).
 *
 *   PG_ADMIN_PASSWORD='...' npm run test:pg-detection
 *
 * Drives pollOnePgPipeline (the REAL orchestrator) against a real source
 * table, with an isolated SQLite for pipeline state. Admin-side mutations
 * (inserts/deletes/RLS/stats reset) run as the postgres superuser — playing
 * the role of the customer's application writing to their own table.
 *
 * Covered: diff-mode init + baseline queue · pg_stat heartbeat idle-skip with
 * ZERO table reads (proven via seq_scan/idx_scan counters) · new-value
 * detection · known-value non-requeue · delete detection via the heartbeat
 * delete counter (needsExportRefresh) · stats-reset fail-open · RLS flag +
 * skip + auto-recover · dropped-table pause.
 */

process.env.PRISM_WAREHOUSE_TYPE = 'postgres';
process.env.PRISM_SQLITE_PATH = `/tmp/prism-pg-det-test-${process.pid}.db`;
process.env.PG_HOST ??= 'localhost';
process.env.PG_DATABASE ??= 'prism_dev';
process.env.PG_USER ??= 'prism_svc';
process.env.PG_PASSWORD ??= 'PrismSvc!Dev1';
process.env.PG_SSLMODE ??= 'disable';
const ADMIN_PASSWORD = process.env.PG_ADMIN_PASSWORD ?? 'PrismDev!Passw0rd';

const { getDb } = await import('../app/api/_lib/sqlite');
const { withAdHocPostgres } = await import('../app/api/_lib/warehouse/postgres/connection');
const { pollOnePgPipeline } = await import('../app/api/_lib/pipeline-poller-postgres');
const { getWarehouseAdapter } = await import('../app/api/_lib/warehouse');

let failures = 0;
function check(name: string, ok: boolean, detail?: unknown): void {
  if (ok) console.log(`  ok    ${name}`);
  else { failures++; console.error(`  FAIL  ${name}${detail !== undefined ? ` — ${JSON.stringify(detail)}` : ''}`); }
}

const adapter = getWarehouseAdapter();
const TBL = 'test_sources.det_test_carriers';
const FQN = `${process.env.PG_DATABASE}.test_sources.det_test_carriers`;
const admin = <T,>(fn: (conn: any) => Promise<T>) =>
  withAdHocPostgres(
    { host: process.env.PG_HOST!, database: process.env.PG_DATABASE!, user: process.env.PG_ADMIN_USER ?? 'postgres', password: ADMIN_PASSWORD, sslmode: 'disable' },
    fn,
  );
const svc = <T,>(fn: (conn: any) => Promise<T>) => adapter.withConnection(fn);

// pg_stat counters flush asynchronously at transaction end — tiny settle wait.
const settle = () => new Promise((r) => setTimeout(r, 700));

// ── Fixture ──────────────────────────────────────────────────────────────────
await admin(async (c) => {
  await c.query(`DROP TABLE IF EXISTS ${TBL}`);
  await c.query(`CREATE TABLE ${TBL} (row_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, carrier VARCHAR(200))`);
  await c.query(`INSERT INTO ${TBL} (carrier) VALUES ('AT&T'), ('ATT'), ('Verizon'), ('VZW'), ('T-Mobile')`);
  await c.query(`GRANT SELECT ON ${TBL} TO prism_service`);
  // Seed one KNOWN value in the lookup so filterUnknownValues has something to exclude.
  await c.query(`DELETE FROM prism_internal.literal_alias_matches WHERE run_id = 990201`);
  await c.query(`DELETE FROM prism_internal.approved_alias_names WHERE alias_name = '__DET_KNOWN__'`);
  await c.query(`INSERT INTO prism_internal.approved_alias_names (alias_name, domain_id) VALUES ('__DET_KNOWN__', 9902)`);
  await c.query(
    `INSERT INTO prism_internal.literal_alias_matches (literal_value, normalized_value, alias_id, domain_id, run_id)
     SELECT 'Verizon', 'verizon', alias_id, 9902, 990201 FROM prism_internal.approved_alias_names WHERE alias_name = '__DET_KNOWN__'`,
  );
  await c.query(`DELETE FROM prism_internal.pipeline_queue WHERE pipeline_id IN (SELECT 990200)`);
});

const db = getDb();
db.prepare(
  `INSERT INTO pipelines (pipeline_id, name, table_fqn, column_name, domain_id, status, update_schedule)
   VALUES (990200, 'det-test', ?, 'carrier', 9902, 'active', '{"type":"always"}')`,
).run(FQN);

const ref = () => {
  const r = db.prepare(`SELECT status, status_message, detection_mode, detection_state, queue_size, total_source_values FROM pipelines WHERE pipeline_id = 990200`).get() as any;
  return { ...r, state: r?.detection_state ? JSON.parse(r.detection_state) : null };
};
const pollRef = () => {
  const r = ref();
  return { pipeline_id: 990200, table_fqn: FQN, column_name: 'carrier', domain_id: 9902, export_table_fqn: null, status_message: r.status_message ?? null };
};
const queueRows = () =>
  svc(async (c) => (await adapter.executeQuery(c, `SELECT literal_value FROM prism_internal.pipeline_queue WHERE pipeline_id = ? ORDER BY literal_value`, [990200])).map((r: any) => String(r.literal_value)));
const sourceReads = () =>
  admin(async (c) => {
    const r = await c.query(`SELECT COALESCE(seq_scan, 0) + COALESCE(idx_scan, 0) AS reads FROM pg_stat_user_tables WHERE schemaname = 'test_sources' AND relname = 'det_test_carriers'`);
    return Number(r.rows[0]?.reads ?? 0);
  });

// ── 1. First poll: init + baseline scan queues unknown values ────────────────
{
  const res = await pollOnePgPipeline(pollRef());
  const r = ref();
  check('first poll checked', res.checked === true, res);
  check('detection_mode persisted as diff', r.detection_mode === 'diff', r.detection_mode);
  check('diff_reason is pg_diff', r.state?.diff_reason === 'pg_diff', r.state);
  const q = await queueRows();
  check('unknown values queued (known “Verizon” excluded)',
    q.length === 4 && q.includes('AT&T') && q.includes('ATT') && q.includes('VZW') && q.includes('T-Mobile') && !q.includes('Verizon'), q);
  check('queue_size metric updated', ref().queue_size === 4, ref().queue_size);
  check('total_source_values counted', ref().total_source_values === 5, ref().total_source_values);
}

// ── 2. Idle poll: heartbeat equal → zero table reads ─────────────────────────
{
  await settle();
  const before = await sourceReads();
  const res = await pollOnePgPipeline(pollRef());
  await settle();
  const after = await sourceReads();
  check('idle poll reports checked', res.checked === true, res);
  check('idle poll did NOT read the source table (seq+idx scans unchanged)', after === before, { before, after });
  check('idle poll flagged no rebuild', res.needsExportRefresh === false);
}

// ── 3. New value: heartbeat moves → scan → queued ────────────────────────────
{
  await admin(async (c) => { await c.query(`INSERT INTO ${TBL} (carrier) VALUES ('Sprint')`); });
  await settle();
  const res = await pollOnePgPipeline(pollRef());
  const q = await queueRows();
  check('new value detected + queued', q.includes('Sprint'), q);
  check('poll after insert reports checked', res.checked === true);
}

// ── 4. New row of a KNOWN value: heartbeat moves, nothing re-queues ──────────
{
  const before = await queueRows();
  await admin(async (c) => { await c.query(`INSERT INTO ${TBL} (carrier) VALUES ('Verizon')`); });
  await settle();
  await pollOnePgPipeline(pollRef());
  const after = await queueRows();
  check('known value does not re-queue (lookup hit excluded)', JSON.stringify(after) === JSON.stringify(before), after);
}

// ── 5. Delete: heartbeat delete-counter delta → hygiene rebuild flag ─────────
{
  await admin(async (c) => { await c.query(`DELETE FROM ${TBL} WHERE carrier = 'ATT'`); });
  await settle();
  const res = await pollOnePgPipeline(pollRef());
  check('delete flags needsExportRefresh (pg heartbeat sees deletes)', res.needsExportRefresh === true, res);
}

// ── 6. Stats reset: backwards counter jump fails OPEN (scan, no crash) ───────
{
  await admin(async (c) => { await c.query(`SELECT pg_stat_reset()`); });
  await settle();
  const res = await pollOnePgPipeline(pollRef());
  check('stats reset tolerated (poll completes, fails open into a scan)', res.checked === true, res);
}

// ── 7. RLS: flag + skip (policy_blocked) + auto-recover ──────────────────────
{
  await admin(async (c) => { await c.query(`ALTER TABLE ${TBL} ENABLE ROW LEVEL SECURITY`); });
  // status_message forces the health check on the next poll (flagged-pipeline
  // cadence); first make one normal poll hit the every-10th health check by
  // simulating the flag path directly:
  const res = await pollOnePgPipeline({ ...pollRef(), status_message: 'force-health-check' });
  const r = ref();
  check('RLS poll skipped (not checked)', res.checked === false, res);
  const reason = db.prepare(`SELECT status_reason, status_message FROM pipelines WHERE pipeline_id = 990200`).get() as any;
  check('RLS flagged with machine-readable policy_blocked', reason?.status_reason === 'policy_blocked', reason);
  check('RLS message names Row-Level Security', String(reason?.status_message ?? '').includes('Row-Level Security'), reason?.status_message);
  check('pipeline NOT paused (skip, not pause)', r.status === 'active', r.status);

  await admin(async (c) => { await c.query(`ALTER TABLE ${TBL} DISABLE ROW LEVEL SECURITY`); });
  const res2 = await pollOnePgPipeline(pollRef()); // status_message set → health re-check → clears
  const cleared = db.prepare(`SELECT status_message, status_reason FROM pipelines WHERE pipeline_id = 990200`).get() as any;
  check('RLS removal auto-recovers (flag cleared)', cleared?.status_message == null && cleared?.status_reason == null, cleared);
  check('post-recovery poll checked', res2.checked === true, res2);
}

// ── 8. Dropped table: pause with message ─────────────────────────────────────
{
  await admin(async (c) => { await c.query(`DROP TABLE ${TBL}`); });
  await pollOnePgPipeline({ ...pollRef(), status_message: 'force-health-check' });
  const r = ref();
  check('dropped table pauses the pipeline', r.status === 'paused', r.status);
  check('pause message mentions access', String(r.status_message ?? '').toLowerCase().includes('access'), r.status_message);
}

// ── Cleanup ──────────────────────────────────────────────────────────────────
await admin(async (c) => {
  await c.query(`DELETE FROM prism_internal.pipeline_queue WHERE pipeline_id = 990200`);
  await c.query(`DELETE FROM prism_internal.literal_alias_matches WHERE run_id = 990201`);
  await c.query(`DELETE FROM prism_internal.approved_alias_names WHERE alias_name = '__DET_KNOWN__'`);
  await c.query(`DROP TABLE IF EXISTS ${TBL}`);
});

if (failures > 0) {
  console.error(`\n${failures} live detection check(s) FAILED`);
  process.exit(1);
}
console.log('\nAll live postgres detection checks passed.');
